// typeship — generated smoke tests for the CLI (dist/cli.js as a real process).
// Generated by typeship — https://typeship.dev
import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { startMock } from "./helper.mjs";

const cli = join(dirname(fileURLToPath(import.meta.url)), "..", "dist", "cli.js");
// async, not spawnSync: the mock answers from this process's event loop.
const run = (args, env = {}) => new Promise((resolve, reject) => {
  const child = spawn(process.execPath, [cli, ...args], { env: { ...process.env, ...env }, stdio: ["ignore", "pipe", "pipe"] });
  let stdout = "";
  let stderr = "";
  child.stdout.on("data", (chunk) => (stdout += chunk));
  child.stderr.on("data", (chunk) => (stderr += chunk));
  child.on("error", reject);
  child.on("close", (status) => resolve({ status, stdout, stderr }));
});

test("typeship --version prints the package and API version", async () => {
  const result = await run(["--version"]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /^typeship \d+\.\d+\.\d+/);
});

test("typeship --help lists resources and exits 0", async () => {
  const result = await run(["--help"]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Resources:/);
});

test("unknown command exits 2 with a suggestion", async () => {
  const result = await run(["definitely-not-a-resource"]);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /Unknown command/);
});

test("typeship generate run round-trips through the mock", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"object\":\"package\",\"files\":[{\"path\":\"example\",\"content\":\"example\",\"mode\":\"100644\"}],\"download\":{\"url\":\"https://example.com\",\"expires_at\":\"2024-01-01T00:00:00Z\",\"sha256\":\"example\",\"size_bytes\":1,\"file_count\":1},\"warnings\":[{\"code\":\"example\",\"message\":\"example\",\"operation\":\"example\"}],\"coverage\":{\"generated\":1,\"omitted\":1,\"total\":1,\"omitted_operations\":[\"example\"],\"reason\":\"anonymous\",\"signup_url\":\"https://example.com\",\"upgrade_url\":\"https://example.com\"},\"claim\":null,\"request_id\":\"req_abcdef0123456789\"}" });
  try {
    const result = await run([...["generate","run","--spec","{}","--target","{}"], "--debug"], { "TYPESHIP_BASE_URL": mock.url, "TYPESHIP_CREDENTIALS": "{\"apiKey\":\"test-token\"}" });
    assert.equal(result.status, 0, result.stderr);
    JSON.parse(result.stdout); // stdout is pure JSON
    assert.match(result.stderr, /req_abcdef0123456789/);
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/generate");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
