// typeship — generated smoke tests for the CLI (dist/cli.js as a real process).
// Generated by typeship — https://typeship.dev — do not edit by hand.
import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { startMock } from "./helper.mjs";

const cli = join(dirname(fileURLToPath(import.meta.url)), "..", "dist", "cli.js");
// async, not spawnSync: the mock answers from this process's event loop.
const run = (args, env = {}) => new Promise((resolve, reject) => {
  const child = spawn(process.execPath, [cli, ...args], { env: { ...process.env, ...env }, stdio: ["ignore", "pipe", "pipe"] });
  let stdout = "";
  let stderr = "";
  child.stdout.on("data", (chunk) => (stdout += chunk));
  child.stderr.on("data", (chunk) => (stderr += chunk));
  child.on("error", reject);
  child.on("close", (status) => resolve({ status, stdout, stderr }));
});

test("typeship --version prints the package and API version", async () => {
  const result = await run(["--version"]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /^typeship \d+\.\d+\.\d+/);
});

test("typeship --help lists resources and exits 0", async () => {
  const result = await run(["--help"]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Resources:/);
});

test("unknown command exits 2 with a suggestion", async () => {
  const result = await run(["definitely-not-a-resource"]);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /Unknown command/);
});

test("typeship generate run round-trips through the mock", async () => {
  const mock = await startMock({ status: 200, contentType: "application/json", body: "{\"files\":[{\"path\":\"example\",\"content\":\"example\"}],\"warnings\":[\"example\"],\"meta\":{\"title\":\"example\",\"api_version\":\"example\",\"version\":\"example\",\"spec_format\":\"openapi\",\"oas_version\":\"example\",\"converted\":true,\"artifact_name\":\"example\",\"client_name\":\"example\",\"generators\":[\"typescript-sdk\"],\"resource_count\":1,\"operation_count\":1,\"schema_count\":1,\"paginated_operation_count\":1,\"omitted_operation_count\":1,\"omitted_operations\":[\"example\"],\"pr_url\":\"example\",\"pr_number\":1,\"pr_status\":\"opened\",\"pr_error\":\"example\",\"changelog\":\"example\",\"breaking_count\":1,\"baseline\":\"destination\",\"api_compatibility\":\"compatible\",\"package_compatibility\":\"compatible\",\"version_correct\":true,\"release_readiness\":\"success\",\"release_readiness_note\":\"example\",\"previous_version\":\"example\",\"file_count\":1,\"total_lines\":1,\"diagnostics\":{\"format\":\"openapi\",\"summary\":{\"diagnostics\":1,\"occurrences\":1,\"errors\":1,\"warnings\":1,\"suggestions\":1,\"auto_fixable\":1}}},\"limits\":{\"max_operations\":1,\"generated_operations\":1,\"omitted_operations\":1,\"total_operations\":1,\"reason\":\"anonymous\",\"signup_url\":\"example\",\"upgrade_url\":\"example\"},\"claim\":null,\"request_id\":\"req_abcdef0123456789\"}" });
  try {
    const result = await run([...["generate","run","--definition","{}","--target","{}"], "--debug"], { "TYPESHIP_BASE_URL": mock.url, "TYPESHIP_TOKEN": "test-token" });
    assert.equal(result.status, 0, result.stderr);
    JSON.parse(result.stdout); // stdout is pure JSON
    assert.match(result.stderr, /req_abcdef0123456789/);
    const request = mock.requests[0];
    assert.equal(request.method, "POST");
    assert.equal(request.path.split("?")[0], "/generate");
    assert.equal(request.headers["authorization"], "Bearer test-token");
  } finally {
    mock.close();
  }
});
