/**
 * `--format table` for the generated CLI: an API result as text for a
 * person at a terminal. Generated by Typeship — https://typeship.dev
 *
 * JSON stays the default and the automation format; this view is opt-in and
 * lossy by design. Lists become columns chosen by name (identifiers, then
 * names, then status-like fields) while they fit the terminal width; a single
 * object becomes one "field  value" line per field in the same order. Cells longer than
 * MAX_CELL characters end in "…", and the footer names every column or field
 * that was left out. Pure: no I/O, so tests render without a terminal.
 */

/** The longest cell before it is cut with "…". */
export const MAX_CELL = 40;
/** A single object shows at most this many (flattened) fields. */
export const MAX_FIELDS = 60;

export interface TableOptions {
  /** Terminal width in columns; lists add columns until it is used. */
  width?: number;
  /** Wraps header text, e.g. in bold when color is on. */
  heading?: (text: string) => string;
  /** The array property that holds a collection response's items ({data: [...]}). */
  collectionField?: string | null;
  /** The command's resource (shipments), so shipment_id is recognized as the row's identifier. */
  resource?: string;
}

type Row = Record<string, unknown>;

const ID_KEYS = new Set(["id", "sid", "uuid", "key", "slug", "code", "symbol", "number", "handle"]);
const NAME_KEYS = new Set(["name", "display_name", "displayname", "friendly_name", "friendlyname", "title", "label", "email", "username", "login", "to", "from"]);
const STATUS_KEYS = new Set(["status", "state"]);
const DESCRIPTOR_KEYS = new Set(["type", "kind", "direction", "enabled", "active", "amount", "currency", "price", "total"]);

/**
 * Lower is shown first: identifiers, names, status, descriptors, everything
 * else, dates, then references and URLs. `primaryId` is the row's own
 * identifier when it is spelled like a reference (shipment_id with no id).
 */
function rank(key: string, primaryId: string | undefined): number {
  const k = key.toLowerCase();
  if (ID_KEYS.has(k) || key === primaryId) return 0;
  if (NAME_KEYS.has(k)) return 1;
  if (STATUS_KEYS.has(k)) return 2;
  if (DESCRIPTOR_KEYS.has(k)) return 3;
  if (/(^|_)(created|updated)(_at|_on)?$|^date_|^(created|updated)|At$/.test(key)) return 5;
  if (/(_id|_sid|Id|_ids|_uri|_url|Url|Uri)$/.test(key) || k === "uri" || k === "url") return 6;
  return 4;
}

/** Keys in display order. The resource's own *_id (shipment_id for shipments) counts as the identifier when no id-like key exists. */
function byRank(keys: string[], resource: string | undefined): string[] {
  const bare = (text: string) => text.toLowerCase().replace(/[^a-z0-9]/g, "");
  const own = resource ? bare(resource).replace(/ies$/, "y").replace(/(ses|xes|s)$/, (m) => m === "s" ? "" : m.slice(0, -2)) + "id" : undefined;
  const primaryId = keys.some((key) => ID_KEYS.has(key.toLowerCase())) ? undefined
    : keys.find((key) => bare(key) === own) ?? keys.find((key) => /(_id|Id)$/.test(key));
  return keys.map((key, index) => ({ key, index, rank: rank(key, primaryId) })).sort((a, b) => a.rank - b.rank || a.index - b.index).map((c) => c.key);
}

function isPlainObject(value: unknown): value is Row {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function scalar(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value.replace(/\s+/g, " ").trim();
  if (typeof value === "number" || typeof value === "boolean" || typeof value === "bigint") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return value.every((v) => v === null || typeof v !== "object") ? value.map(scalar).join(", ") : "[" + value.length + " items]";
  }
  if (isPlainObject(value)) {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    return entries.every(([, v]) => v === null || typeof v !== "object")
      ? entries.map(([k, v]) => k + "=" + scalar(v)).join(" ")
      : "{" + entries.length + " fields}";
  }
  return String(value);
}

function cut(text: string, max: number): string {
  return text.length > max ? text.slice(0, Math.max(1, max - 1)) + "…" : text;
}

function pad(text: string, width: number): string {
  return text + " ".repeat(Math.max(0, width - text.length));
}

/** The rows and footer lines of a list-shaped result, or null for a single object. */
function listOf(value: unknown, collectionField: string | null | undefined): { rows: unknown[]; footer: string[] } | null {
  if (Array.isArray(value)) return { rows: value, footer: [] };
  if (!isPlainObject(value)) return null;
  // The CLI's page envelope: {items, hasMore, nextPage?, nextCommand?, request_id?}.
  if (Array.isArray(value.items) && typeof value.hasMore === "boolean") {
    return { rows: value.items, footer: typeof value.nextCommand === "string" ? ["More results: " + value.nextCommand] : [] };
  }
  if (collectionField && Array.isArray(value[collectionField])) {
    const rest = Object.entries(value).filter(([k, v]) => k !== collectionField && v !== null && typeof v !== "object");
    return { rows: value[collectionField] as unknown[], footer: rest.length ? [rest.map(([k, v]) => k + ": " + scalar(v)).join("  ")] : [] };
  }
  return null;
}

function renderRows(rows: unknown[], footer: string[], options: TableOptions): string {
  const heading = options.heading ?? ((text: string) => text);
  if (rows.length === 0) return ["No items.", ...footer].join("\n") + "\n";
  if (!rows.every(isPlainObject)) {
    return [...rows.map((row) => cut(scalar(row), Math.max(MAX_CELL, options.width ?? 120))), "", rows.length + (rows.length === 1 ? " item" : " items"), ...footer].join("\n") + "\n";
  }
  const keys: string[] = [];
  for (const row of rows as Row[]) for (const key of Object.keys(row)) if (!keys.includes(key)) keys.push(key);
  const ordered = byRank(keys, options.resource);
  const width = Math.max(40, options.width ?? 120);
  const shown: { key: string; width: number }[] = [];
  let used = 0;
  for (const key of ordered) {
    const cells = (rows as Row[]).map((row) => cut(scalar(row[key]), MAX_CELL));
    // A column empty in every row says nothing.
    if (cells.every((cell) => cell === "")) continue;
    const columnWidth = Math.max(Math.min(key.length, MAX_CELL), ...cells.map((cell) => cell.length));
    if (shown.length > 0 && used + 2 + columnWidth > width) continue;
    shown.push({ key, width: columnWidth });
    used += (shown.length > 1 ? 2 : 0) + columnWidth;
  }
  const line = (cells: string[]) => cells.map((cell, i) => i === cells.length - 1 ? cell : pad(cell, shown[i]!.width)).join("  ").trimEnd();
  const lines = [
    heading(line(shown.map((c) => cut(c.key.toUpperCase(), c.width)))),
    ...(rows as Row[]).map((row) => line(shown.map((c) => cut(scalar(row[c.key]), MAX_CELL)))),
    "",
  ];
  const hidden = ordered.filter((key) => !shown.some((c) => c.key === key));
  lines.push(rows.length + (rows.length === 1 ? " item" : " items") + (hidden.length ? "; not shown: " + hidden.join(", ") : ""));
  return [...lines, ...footer].join("\n") + "\n";
}

/** One object as "field  value" lines, identifiers and status first; nested objects flatten to dotted paths. */
function renderObject(value: Row, options: TableOptions): string {
  const fields: [string, string][] = [];
  const walk = (object: Row, prefix: string, depth: number) => {
    const keys = depth === 0 ? byRank(Object.keys(object), options.resource) : Object.keys(object);
    for (const key of keys) {
      const v = object[key];
      const path = prefix + key;
      if (isPlainObject(v) && depth < 2 && Object.keys(v).length > 0) walk(v, path + ".", depth + 1);
      else fields.push([path, scalar(v)]);
    }
  };
  walk(value, "", 0);
  if (fields.length === 0) return "No fields.\n";
  const heading = options.heading ?? ((text: string) => text);
  const shown = fields.slice(0, MAX_FIELDS);
  const keyWidth = Math.min(MAX_CELL, Math.max(...shown.map(([key]) => key.length)));
  const valueWidth = Math.max(MAX_CELL, (options.width ?? 120) - keyWidth - 2);
  const lines = shown.map(([key, text]) => (heading(pad(cut(key, keyWidth), keyWidth)) + "  " + cut(text, valueWidth)).trimEnd());
  if (fields.length > shown.length) lines.push("", (fields.length - shown.length) + " more fields not shown; use --format json or --fields.");
  return lines.join("\n") + "\n";
}

/** The text --format table prints for a result that would otherwise print as JSON. */
export function renderTable(value: unknown, options: TableOptions = {}): string {
  const list = listOf(value, options.collectionField);
  if (list) return renderRows(list.rows, list.footer, options);
  if (isPlainObject(value)) return renderObject(value, options);
  return scalar(value) + "\n";
}
